export const direcciones = [
  {
    usuario_id: 1,
    provincia: "Alajuela",
    provinciaid :2,
    canton: "Central",
    cantonid:1,
    distrito: "Carrizal",
    distritoid:3,
    direccion_exacta: "Urbanizacion Los Portones",
    codigo_postal: "2018",
    telefono: "7269-6157",
    eliminado: false,
  },
  {
    usuario_id: 2,
    provincia: "San Jose",
    provinciaid :1,
    canton: "Tibas",
    cantonid:13,
    distrito: "San Juan",
    distritoid:1,
    direccion_exacta: "Calle #3",
    codigo_postal: "2018",
    telefono: "7269-6157",
    eliminado: false,
  },
  {
    usuario_id: 3,
    provincia: "Heredia",
    provinciaid :4,
    canton: "Central",
    cantonid:1,
    distrito: "Mercedes",
    distritoid:2,
    direccion_exacta: "Calle #5",
    codigo_postal: "2018",
    telefono: "7269-6157",
    eliminado: false,
  },

  //Nuevos usuarios

  {
    usuario_id: 10,
    provincia: "Heredia",
    provinciaid :4,
    canton: "Central",
    cantonid:1,
    distrito: "Mercedes",
    distritoid:2,
    direccion_exacta: "Calle #5",
    codigo_postal: "2018",
    telefono: "7269-6157",
    eliminado: false,
  },
  {
    usuario_id: 11,
    provincia: "Heredia",
    provinciaid :4,
    canton: "Central",
    cantonid:1,
    distrito: "Mercedes",
    distritoid:2,
    direccion_exacta: "Calle #5",
    codigo_postal: "2018",
    telefono: "7269-6157",
    eliminado: false,
  },
  {
    usuario_id: 12,
    provincia: "Heredia",
    provinciaid :4,
    canton: "Central",
    cantonid:1,
    distrito: "Mercedes",
    distritoid:2,
    direccion_exacta: "Calle #5",
    codigo_postal: "2018",
    telefono: "7269-6157",
    eliminado: false,
  },
  {
    usuario_id: 13,
    provincia: "Heredia",
    provinciaid :4,
    canton: "Central",
    cantonid:1,
    distrito: "Mercedes",
    distritoid:2,
    direccion_exacta: "Calle #5",
    codigo_postal: "2018",
    telefono: "7269-6157",
    eliminado: false,
  },
  {
    usuario_id: 14,
    provincia: "Heredia",
    provinciaid :4,
    canton: "Central",
    cantonid:1,
    distrito: "Mercedes",
    distritoid:2,
    direccion_exacta: "Calle #5",
    codigo_postal: "2018",
    telefono: "7269-6157",
    eliminado: false,
  },
];
